"我的vim配置
"===========

set nocompatible "禁用vi兼容模式

"编码相关
set fileformats=unix
set fileencodings=utf-8,gb2312,gbk,gb18030 "Vim 打开文件时尝试使用的编码
set encoding=utf-8 "Vim 的内部编码
set fileencoding=utf-8 "Vim当前编辑的文件在存储时的编码
"set termencoding=utf-8 "Vim 在与屏幕/键盘交互时使用的编码(取决于实际的终端的设定)

set helplang=cn "使用中文帮助文档

syntax on "语法高亮
"vim高亮的配色方案(desert,delek,torte)
colo desert
"colo elflord
"colorscheme ron
"colorscheme torte
"colorscheme murphy

set nu "显示行号

set wrap "自动折行
"set autoread   "文件在Vim之外修改过，自动重新读入

" Tab related
set expandtab "在缩进和遇到Tab键时,使用空格替代,宽度为4个空格, set et
set tabstop=4 "定义tab符占用的空格长度, set ts=2
set shiftwidth=4 "缩进的空格数为4, set sw=2
set softtabstop=4 "方便在开启了et后使用退格（backspace）键，每次退格将删除x个空格, set sts=4

set autoindent "自动对齐，使用上一行的对齐方式
set smartindent "智能缩进

"文件类型检测，plugin支持状态，不同文件类型选择合适的缩进方式
"filetype on
"filetype plugin on
"filetype indent on
filetype plugin indent on
"根据文件类型设置缩进格式
"autocmd FileType html,javascript,less,css setlocal et ts=2 sw=2 sts=2
au FileType html,javascript,less,css setl et ts=2 sw=2 sts=2

set ruler "在右下角显示光标位置

set foldmethod=indent "折叠

""命令收集
"使php识别EOT字符串
hi link phpheredoc string

"markdown语法高亮
au BufRead,BufNewFile *.{md,mdown,mkd,mkdn,markdown,mdwn} set filetype=mkd
let g:vim_markdown_folding_disabled=1

"高亮显示行尾的空格 ctermbg=red时,空格反白显示
highlight WhitespaceEOL ctermbg=red guibg=red
highlight WhitespaceEOL ctermbg=red
match WhitespaceEOL /\s\+$/

set hlsearch "高亮显示搜索结果,关闭:set nohls
set incsearch "搜索自动定位
set ignorecase "忽略大小写(查找字符串时)

set showcmd "显示未敲完的命令
"set cmdheight=2 "设定命令行（在状态行下）的高度，默认为1，这里是2

set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%Y-%m-%d\ -\ %H:%M\")}   "状态行显示的内容
set laststatus=1 "启动显示状态行(1),总是显示状态行(2)

"conf for tabs, 为标签页进行的配置，通过ctrl h/l切换标签等
nnoremap <C-h> gT
nnoremap <C-l> gt


"防止特殊符号无法正常显示
set ambiwidth=double

"解决粘贴到终端Vim缩进错乱的问题 set paste, set nopaste
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>

" 在命令模式下使用 Tab 自动补全的时候，将补全内容使用一个漂亮的单行菜单形式显示出来
set wildmenu

"Experimental
" 在什么情况下使用鼠标:normal/visual/insert/cmd/help/r/all
"set mouse=a  "bug:无法复制

"当前行高亮
set cursorline
hi CursorLine cterm=NONE ctermbg=black ctermfg=NONE

"set showmatch "设置匹配模式，类似当输入一个左括号时匹配上相应的那个右括号"
